MvcNetCoreLinqToSql/Models/Departamento.cs
namespace MvcNetCoreLinqToSql.Models
{
    public class Departamento
    {
        public int DeptNo { get; set; }
        public string DeptNombre { get; set; }
        public string Localidad { get; set; }
    }
}

MvcNetCoreLinqToSql/Models/Empleado.cs
namespace MvcNetCoreLinqToSql.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public int Salario { get; set; }
        public int IdDepartamento { get; set; }
    }
}

MvcNetCoreLinqToSql/Models/Enfermo.cs
namespace MvcNetCoreLinqToSql.Models
{
    public class Enfermo
    {
        public int Inscripcion { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public int NSS { get; set; }
    }
}

MvcNetCoreLinqToSql/Models/ErrorViewModel.cs
namespace MvcNetCoreLinqToSql.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCoreLinqToSql/Models/ResumenEmpleados.cs
namespace MvcNetCoreLinqToSql.Models
{
    public class ResumenEmpleados
    {
        public int Personas { get; set; }
        public int MaximoSalario { get; set; }
        public double MediaSalarial { get; set; }
        public List<Empleado> Empleados { get; set; }
    }
}

MvcNetCoreLinqToSql/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreLinqToSql.Models;
using MvcNetCoreLinqToSql.Repositories;

namespace MvcNetCoreLinqToSql.Controllers
{
    public class EmpleadosController : Controller
    {
        private RepositoryEmpleados repo;

        public EmpleadosController()
        {
            this.repo = new RepositoryEmpleados();
        }

        public IActionResult Index()
        {
            List<Empleado> empleados = this.repo.GetEmpleados();
            return View(empleados);
        }

        public IActionResult Details(int id)
        {
            Empleado empleado = this.repo.FindEmpleado(id);
            return View(empleado);
        }

        public IActionResult BuscadorEmpleados()
        {
            List<Empleado> empleados = this.repo.GetEmpleados();
            return View(empleados);
        }

        [HttpPost]
        public IActionResult BuscadorEmpleados(string oficio, int salario)
        {
            List<Empleado> empleados = this.repo.GetEmpleadosOficioSalario(oficio, salario);
            if (empleados == null)
            {
                ViewData["MENSAJE"] = "No se encontraron registros con oficio " + oficio + " y salario mayor a " + salario;
                return View();
            }
            return View(empleados);
        }

        public IActionResult DatosEmpleados()
        {
            ViewData["OFICIOS"] = this.repo.GetOficios();
            return View();
        }

        [HttpPost]
        public IActionResult DatosEmpleados(string oficio)
        {
            ViewData["OFICIOS"] = this.repo.GetOficios();
            ResumenEmpleados resumen = this.repo.GetEmpleadosOficio(oficio);
            return View(resumen);
        }

        public IActionResult EmpleadosDepartamento()
        {
            ViewData["DEPT"] = this.repo.GetDepartamentos();
            return View();
        }

        [HttpPost]
        public IActionResult EmpleadosDepartamento(int dept_no)
        {
            ViewData["DEPT"] = this.repo.GetDepartamentos();
            ResumenEmpleados resumen = this.repo.GetEmpleadosDept(dept_no);
            if (resumen == null)
            {
                ViewData["MENSAJE"] = "No se encontraron empleados del departamento " + dept_no;
                return View();
            }
            return View(resumen);
        }
    }
}

MvcNetCoreLinqToSql/Controllers/EnfermosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreLinqToSql.Models;
using MvcNetCoreLinqToSql.Repositories;

namespace MvcNetCoreLinqToSql.Controllers
{
    public class EnfermosController : Controller
    {
        private RepositoryEnfermos repo;

        public EnfermosController()
        {
            this.repo = new RepositoryEnfermos();
        }

        public IActionResult Index()
        {
            List<Enfermo> enfermos = this.repo.GetEnfermos();
            return View(enfermos);
        }

        public IActionResult Details(int id)
        {
            Enfermo enfermo = this.repo.FindEnfermo(id);
            return View(enfermo);
        }

        public IActionResult Delete(int id)
        {
            this.repo.DeleteEnfermo(id);
            return RedirectToAction("Index");
        }
    }
}

MvcNetCoreLinqToSql/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreLinqToSql.Models;
using System.Diagnostics;

namespace MvcNetCoreLinqToSql.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCoreLinqToSql/Views/Empleados/BuscadorEmpleados.cshtml
@model List<Empleado>

<h1>Buscador Empleados</h1>

<form method="post">
    <label class="form-label mt-3">Oficio</label>
    <input type="text" name="oficio" class="form-control" required />
    <label class="form-label mt-3">Salario</label>
    <input type="number" name="salario" class="form-control" required />
    <button class="btn btn-info mt-3">Buscar</button>
</form>

<h3 class="text-center w-75 mx-auto mt-3" style="color: red">@ViewData["MENSAJE"]</h3>
@if (Model != null)
{
    <table class="table table-borderless mt-3">
        <thead>
            <tr>
                <th>Apellido</th>
                <th>Oficio</th>
                <th>Salario</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Empleado emple in Model)
            {
                <tr>
                    <td>@emple.Apellido</td>
                    <td>@emple.Oficio</td>
                    <td>@emple.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}

MvcNetCoreLinqToSql/Views/Empleados/DatosEmpleados.cshtml
@model ResumenEmpleados

@{
    List<string> oficios = ViewData["OFICIOS"] as List<string>;
}

<h1>Lambda Empleados Oficio</h1>

<form class="mt-3" method="post">
    <label class="form-label">Introduzca un oficio</label>
    <select name="oficio" class="form-select">
        @foreach (string oficio in oficios)
        {
            <option value="@oficio">@oficio</option>
        }
    </select>
    <button class="btn btn-outline-success mt-3">
        Mostrar resumen
    </button>
</form>

@if (Model != null)
{
    <ul class="list-group mt-3">
        <li class="list-group-item">
            <span class="fw-bold">Personas:</span> @Model.Personas
        </li>
        <li class="list-group-item">
            <span class="fw-bold">Máximo:</span> @Model.MaximoSalario
        </li>
        <li class="list-group-item">
            <span class="fw-bold">Media:</span> @Model.MediaSalarial
        </li>
    </ul>
    <table class="table table-borderless mt-3">
        <tr>
            <th>Apellido</th>
            <th>Oficio</th>
            <th>Salario</th>
        </tr>


        <tbody>
            @foreach (Empleado emp in Model.Empleados)
            {
                <tr>
                    <td>@emp.Apellido</td>
                    <td>@emp.Oficio</td>
                    <td>@emp.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}

MvcNetCoreLinqToSql/Views/Empleados/Details.cshtml
@model Empleado

<h1>Details</h1>

<p>
    <a asp-controller="Empleados" asp-action="Index">Back to Index</a>
</p>

<ul class="list-group">
    <li class="list-group-item">Apellido: @Model.Apellido</li>
    <li class="list-group-item">Oficio: @Model.Oficio</li>
    <li class="list-group-item">Salario: @Model.Salario</li>
</ul>

MvcNetCoreLinqToSql/Views/Empleados/EmpleadosDepartamento.cshtml
@model ResumenEmpleados
@*adsa*@
@{
    // List<int> departamentos = ViewData["DEPT"] as List<int>;
    List<Departamento> departamentos = ViewData["DEPT"] as List<Departamento>;
}

<h1>Empleados por departamento</h1>

<form method="post">
    <label class="form-label">Departamento</label>
    <select class="form-select" name="dept_no">
        @*
        @foreach (int depart in departamentos)
        {
        <option value="@depart">@depart</option>
        }
        *@
        @foreach (Departamento depart in departamentos)
        {
            <option value="@depart.DeptNo">@depart.DeptNombre</option>
        }
    </select>
    <button class="btn btn-outline-info mt-3">Buscar</button>
</form>

<h3 class="text-center mx-auto w-75 mt-3" style="color:red">@ViewData["MENSAJE"]</h3>

@if (Model != null)
{
    <table class="table table-borderless">
        <thead>
            <tr>
                <th>Apellido</th>
                <th>Num dept</th>
                <th>Oficio</th>
                <th>Salario</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Empleado emple in Model.Empleados)
            {
                <tr>
                    <td>@emple.Apellido</td>
                    <td>@emple.IdDepartamento</td>
                    <td>@emple.Oficio</td>
                    <td>@emple.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}

MvcNetCoreLinqToSql/Views/Empleados/Index.cshtml
@model List<Empleado>

<h1>Empleados LINQ</h1>


<div class="row">
    <a asp-controller="Empleados" asp-action="BuscadorEmpleados"
       class="btn btn-success mt-3">
        Buscador empleados
    </a>
    <a asp-controller="Empleados" asp-action="DatosEmpleados"
       class="btn btn-success mt-3">
        Empleados por oficio
    </a>
    <a asp-controller="Empleados" asp-action="EmpleadosDepartamento"
       class="btn btn-success mt-3">
        Empleados por departamento
    </a>
</div>

<ul class="list-group mt-3">
    @foreach (Empleado emp in Model)
    {
        <li class="list-group-item">
            @emp.Apellido - @emp.Oficio
            <a asp-controller="Empleados" asp-action="Details"
               asp-route-id="@emp.IdEmpleado" class="btn btn-sm btn-primary ms-4">
                Details
            </a>
        </li>
    }
</ul>

MvcNetCoreLinqToSql/Views/Enfermos/Details.cshtml
@model Enfermo

<h1>Detalles</h1>

<a asp-controller="Enfermos" asp-action="Index"
   class="btn btn-primary mt-3">Volver al Index</a>

<ul class="list-group mt-3">
    <li class="list-group-item">Inscripción: @Model.Inscripcion</li>
    <li class="list-group-item">Apellido: @Model.Apellido</li>
    <li class="list-group-item">Dirección: @Model.Direccion</li>
    <li class="list-group-item">Fecha Nacimiento: @Model.FechaNacimiento</li>
    <li class="list-group-item">Sexo: @Model.Sexo</li>
    <li class="list-group-item">NSS: @Model.NSS</li>
</ul>

MvcNetCoreLinqToSql/Views/Enfermos/Index.cshtml
@model List<Enfermo>

<h1>Enfermos</h1>
<table class="table table-borderless">
    <thead>
        <tr>
            <th>Apellido</th>
            <th>Fecha Nacimiento</th>
            <th>Sexo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Enfermo enfermo in Model)
        {
            <tr>
                <td>@enfermo.Apellido</td>
                <td>@enfermo.FechaNacimiento</td>
                <td>@enfermo.Sexo</td>
                <td>
                    <a asp-controller="Enfermos" asp-action="Details"
                       asp-route-id="@enfermo.Inscripcion" class="btn btn-primary btn-sm">
                        Details
                    </a>
                    <a asp-controller="Enfermos" asp-action="Delete"
                       asp-route-id="@enfermo.Inscripcion" class="btn btn-danger btn-sm">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

MvcNetCoreLinqToSql/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcNetCoreLinqToSql/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreLinqToSql</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCoreLinqToSql.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNetCoreLinqToSql</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Empleados" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Enfermos" asp-action="Index">Enfermos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcNetCoreLinqToSql - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>